CREATE TYPE probleem_type AS ENUM ('Technisch', 'Esthetisch', 'Service/Levering', 'Andere');

CREATE TYPE klacht_status AS ENUM ('Ingediend', 'Goedgekeurd', 'Afgewezen', 'In behandeling', 'Afgehandeld');

CREATE TYPE gebruikersrol AS ENUM ('User', 'Admin', 'Key user');

create table gebruiker (
  gebruiker_id serial not null,
  naam text not null,
  email text not null,
  rol gebruikersrol not null,
  wachtwoord text not null,
  telefoon text null,
  businessunit_id integer null,
  constraint gebruiker_pkey primary key (gebruiker_id),
  constraint gebruiker_email_key unique (email),
  constraint gebruiker_businessunit_id_fkey foreign KEY (businessunit_id) references businessunit (businessunit_id)
) 

create table businessunit (
  businessunit_id serial not null,
  naam text not null,
  constraint businessunit_pkey primary key (businessunit_id)
) 

create table klacht (
  klacht_id serial not null,
  verantwoordelijke_id integer not null,
  klant_id integer not null,
  categorie_id integer not null,
  mogelijke_oorzaak text null,
  bijlages text null,
  prioriteit boolean null default false,
  status klacht_status null default 'Ingediend'::klacht_status,
  datum_melding timestamp with time zone null default now(),
  klacht_omschrijving text not null,
  opmerking_status_wijziging text null,
  datum_laatst_bewerkt timestamp with time zone null default now(),
  order_nummer character varying(255) not null,
  artikelnummer serial null,
  aantal_eenheden smallint null,
  businessunit_id serial null,
  constraint klacht_pkey primary key (klacht_id),
  constraint klacht_businessunit_id_fkey foreign KEY (businessunit_id) references businessunit (businessunit_id),
  constraint klacht_categorie_id_fkey foreign KEY (categorie_id) references probleemcategorie (categorie_id) on delete set null,
  constraint klacht_artikelnummer_fkey foreign KEY (artikelnummer) references product (artikel_nr),
  constraint klacht_order_nummer_fkey foreign KEY (order_nummer) references "order" (order_nummer),
  constraint klacht_vertegenwoordiger_id_fkey foreign KEY (verantwoordelijke_id) references gebruiker (gebruiker_id),
  constraint klacht_klant_id_fkey foreign KEY (klant_id) references klant (klant_id) on delete set null
) 

create table klant (
  klant_id serial not null,
  klantnaam text not null,
  contactpersoon text null,
  email text null,
  telefoon text null,
  adres text null,
  ondernemingsnummer bigint null,
  constraint klant_pkey primary key (klant_id)
)

create table order (
  order_nummer character varying not null,
  created_at timestamp with time zone not null default now(),
  klant_id serial not null,
  constraint order_pkey primary key (order_nummer),
  constraint order_klant_id_fkey foreign KEY (klant_id) references klant (klant_id)
)

create table probleemcategorie (
  categorie_id serial not null,
  type probleem_type not null,
  constraint probleemcategorie_pkey primary key (categorie_id)
) 

create table product (
  artikel_nr serial generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  naam text not null,
  constraint product_pkey primary key (artikel_nr)
)

create table producten_order (
  order_nummer character varying not null,
  artikel_nr serial not null,
  aantal integer not null,
  created_at timestamp with time zone not null default now(),
  constraint producten_order_pkey primary key (order_nummer, artikel_nr),
  constraint producten_order_artikel_nr_fkey foreign KEY (artikel_nr) references product (artikel_nr),
  constraint producten_order_order_nummer_fkey foreign KEY (order_nummer) references "order" (order_nummer)
)

create table statushistoriek (
  status_id serial not null,
  klacht_id integer not null,
  oude_status klacht_status not null,
  nieuwe_status klacht_status not null,
  gewijzigd_door integer null,
  opmerking text null,
  datum_wijziging timestamp with time zone null default now(),
  constraint statushistoriek_pkey primary key (status_id),
  constraint status_historiek_gewijzigd_door_fkey foreign KEY (gewijzigd_door) references gebruiker (gebruiker_id),
  constraint status_historiek_klacht_id_fkey foreign KEY (klacht_id) references klacht (klacht_id) on delete CASCADE
)

